export const questions = [
  {
    id: 1,
    text: "Bør staten redusere sin rolle i økonomien og overlate mer til det frie markedet?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 2,
    text: "Bør staten redusere eller fjerne formueskatten for å fremme næringsliv og investeringer?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 3,
    text: "Bør pensjoner kun organiseres gjennom private ordninger uten statlig innblanding?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 4,
    text: "Bør Norge innføre mer direkte demokrati, som folkets rett til å foreslå og stemme over lover?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 5,
    text: "Bør mer makt overføres fra staten til lokalstyrene for å styre egne ressurser og lokale saker?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 6,
    text: "Bør Norge bli medlem av EU?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 7,
    text: "Bør Norge trekke seg fra EØS-avtalen for å styrke nasjonal suverenitet og selvbestemmelse?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 8,
    text: "Bør staten begrense flyktning- og asylinnvandringen?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 9,
    text: "Bør staten fortsette å finansiere internasjonale bistandsmidler?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 10,
    text: "Bør Norge prioritere olje- og gassutvinning for å sikre nasjonal økonomi fremfor å begrense det på grunn av klima?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 11,
    text: "Bør klimaendringer prioriteres høyere enn økonomisk vekst i politiske beslutninger?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 12,
    text: "Bør staten øke satsingen på grønn teknologi for å skape nye arbeidsplasser?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 13,
    text: "Bør staten ha mindre innflytelse over skolenes læreplaner for å unngå ideologisk styring?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 14,
    text: "Bør staten avstå fra å finansiere nyhetsmedier og organisasjoner knyttet til kultur, livssyn og religion for å sikre uavhengighet og skille staten fra disse områdene?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 15,
    text: "Bør staten begrense regulering av ytringsfrihet, både i lovverk og på digitale plattformer?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
  {
    id: 16,
    text: "Bør Norge forbli i NATO for å sikre nasjonal sikkerhet?",
    options: [
      { id: "A", text: "Sterkt for", value: 2 },
      { id: "B", text: "For", value: 1 },
      { id: "C", text: "Nøytral", value: 0 },
      { id: "D", text: "Mot", value: -1 },
      { id: "E", text: "Sterkt mot", value: -2 },
    ],
  },
];

export const parties = {
  "Norgesdemokratene": { name: "Norgesdemokratene", description: "Parti med fokus på nasjonale interesser og innvandringskontroll." },
  "Konservativt": { name: "Konservativt", description: "Konservativt parti med fokus på tradisjonelle verdier og markedsøkonomi." },
  "Generasjonspartiet": { name: "Generasjonspartiet", description: "Parti med fokus på generasjonspolitikk." },
  "Industri- og Næringspartiet": { name: "Industri- og Næringspartiet", description: "Parti med fokus på industri og næringsutvikling." },
  "Partiet DNI": { name: "Partiet DNI", description: "Parti med fokus på direkte demokrati og nasjonale interesser." },
  "Pensjonistpartiet": { name: "Pensjonistpartiet", description: "Parti med fokus på pensjonisters rettigheter." },
  "Partiet Sentrum": { name: "Partiet Sentrum", description: "Sentrumsparti med fokus på sosial rettferdighet og miljø." },
  "Velferd og Innovasjonspartiet": { name: "Velferd og Innovasjonspartiet", description: "Parti med fokus på velferd og innovasjon." },
  "FOR": { name: "Fred og Rettferdighet", description: "Parti med fokus på fred og rettferdighet." },
  "Ensomhetspartiet": { name: "Ensomhetspartiet", description: "Parti med fokus på å bekjempe ensomhet." },
  "AP": { name: "Arbeiderpartiet", description: "Sosialdemokratisk parti med fokus på velferd og likhet." },
  "FrP": { name: "Fremskrittspartiet", description: "Høyrepopulistisk parti som fokuserer på lavere skatter og innvandringskontroll." },
  "H": { name: "Høyre", description: "Konservativt parti som støtter frie markeder og individuelt ansvar." },
  "Sp": { name: "Senterpartiet", description: "Sentrumsparti med fokus på distriktspolitikk og landbruk." },
  "KrF": { name: "Kristelig Folkeparti", description: "Kristendemokratisk parti med fokus på familieverdier og velferd." },
  "V": { name: "Venstre", description: "Liberalt parti med fokus på frihet og miljø." },
  "SV": { name: "SV - Sosialistisk Venstreparti", description: "Sosialistisk parti med fokus på velferd og miljø." },
  "R": { name: "Rødt", description: "Venstresideparti med fokus på sosialisme og likhet." },
  "MDG": { name: "Miljøpartiet De Grønne", description: "Miljøparti med fokus på bærekraft og grønn politikk." },
};

export const partyPositions = {
  "Norgesdemokratene": [2, 2, 2, 2, 2, -2, 2, 2, -2, 2, -2, -2, 2, 2, 2, 2],
  "Konservativt": [2, 2, 2, 2, 2, -2, 2, 2, -2, 2, -2, -2, 2, 2, 2, 2],
  "Generasjonspartiet": [-2, -2, -2, 1, 1, 1, -2, -2, 1, -2, 1, 1, -2, -2, -2, 1],
  "Industri- og Næringspartiet": [2, 2, 2, 2, 2, -2, 2, 2, -2, 2, -2, -2, 2, 2, 2, 2],
  "Partiet DNI": [2, 2, 2, 2, 2, -2, 2, 2, -2, 2, -2, -2, 2, 2, 2, 2],
  "Pensjonistpartiet": [-2, -2, -2, 1, 1, -2, -2, 1, 1, -2, 1, 1, -2, -2, -2, 1],
  "Partiet Sentrum": [-2, -2, -2, 1, 1, 1, -2, -2, 1, -2, 1, 1, -2, -2, -2, 1],
  "Velferd og Innovasjonspartiet": [-2, -2, -2, 1, 1, 1, -2, -2, 1, -2, 1, 1, -2, -2, -2, 1],
  "FOR": [-2, -2, -2, 1, 1, 1, -2, -2, 1, -2, 1, 1, -2, -2, -2, -2],
  "Ensomhetspartiet": [-2, -2, -2, 1, 1, -2, -2, -2, 1, -2, 1, 1, -2, -2, -2, 1],
  "AP": [-2, -2, -2, 1, 1, 1, -2, -2, 1, -2, 1, 1, -2, -2, -2, 1],
  "FrP": [2, 2, 2, 2, 2, -2, 2, 2, -2, 2, -2, -2, 2, 2, 2, 2],
  "H": [1, 1, 1, -1, 0, 1, -2, 1, 1, 1, -1, 1, 1, 1, 1, 1],
  "Sp": [-2, -2, -2, 1, 2, -2, 0, 1, 1, 1, -1, 1, -2, -2, -2, 1],
  "KrF": [-2, -2, -2, 1, 1, -2, 0, 1, 1, -2, 1, 1, -2, -2, -2, 1],
  "V": [1, 1, 1, 1, 1, 1, -2, -1, 1, -2, 1, 1, 1, 1, 1, 1],
  "SV": [-2, -2, -2, 1, 1, 1, -2, -2, 1, -2, 1, 1, -2, -2, -2, 1],
  "R": [-2, -2, -2, 1, 1, -1, 1, -2, 1, -2, 1, 1, -2, -2, -2, -2],
  "MDG": [-2, -2, -2, 1, 1, 1, -2, -2, 1, -2, 2, 2, 0, 0, 1, 1],
};