export const questions = [
  {
    id: 1,
    text: "Bør staten redusere sin rolle i økonomien og overlate mer til det frie markedet?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["Konservativt"] },
      { id: "B", text: "For", value: 1, parties: ["Norgesdemokratene", "FrP", "Industri- og Næringspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["H", "V", "Partiet DNI", "Ensomhetspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: ["KrF", "Generasjonspartiet"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["AP", "SV", "R", "MDG", "FOR", "Sp", "Partiet Sentrum", "Pensjonistpartiet", "Velferd og Innovasjonspartiet"] },
    ],
  },
  {
    id: 2,
    text: "Bør staten redusere eller fjerne formueskatten for å fremme næringsliv og investeringer?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["Norgesdemokratene", "Konservativt", "Partiet DNI"] },
      { id: "B", text: "For", value: 1, parties: ["FrP", "Industri- og Næringspartiet", "Generasjonspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["H", "V", "Ensomhetspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: ["KrF", "Sp", "Pensjonistpartiet", "Velferd og Innovasjonspartiet"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["AP", "SV", "R", "MDG", "FOR", "Partiet Sentrum"] },
    ],
  },
  {
    id: 3,
    text: "Bør private pensjonsordninger få en større rolle som et alternativ til statlige ordninger?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["Konservativt"] },
      { id: "B", text: "For", value: 1, parties: ["Industri- og Næringspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["FrP", "H", "Norgesdemokratene", "Ensomhetspartiet", "Generasjonspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: ["AP", "KrF", "V", "Sp"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["SV", "R", "MDG", "FOR", "Partiet Sentrum", "Pensjonistpartiet", "Velferd og Innovasjonspartiet"] },
    ],
  },
  {
    id: 4,
    text: "Bør Norge innføre mer direkte demokrati, som folkets rett til å foreslå og stemme over lover?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["Norgesdemokratene", "Generasjonspartiet"] },
      { id: "B", text: "For", value: 1, parties: ["Konservativt", "MDG", "SV", "Industri- og Næringspartiet", "FrP", "R", "Velferd og Innovasjonspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["FOR", "Partiet DNI", "Partiet Sentrum", "Pensjonistpartiet", "Ensomhetspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: [] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["AP", "KrF", "Sp", "V", "H"] },
    ],
  },
  {
    id: 5,
    text: "Bør mer makt overføres fra staten til lokalstyrene for å styre egne ressurser og lokale saker?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["Norgesdemokratene", "Konservativt", "Generasjonspartiet", "FrP", "Sp"] },
      { id: "B", text: "For", value: 1, parties: ["Industri- og Næringspartiet", "Partiet DNI", "Partiet Sentrum", "Pensjonistpartiet", "Velferd og Innovasjonspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["KrF", "SV", "R", "Ensomhetspartiet", "FOR"] },
      { id: "D", text: "Mot", value: -1, parties: ["MDG"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["AP", "H", "V"] },
    ],
  },
  {
    id: 6,
    text: "Bør Norge bli medlem av EU?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["AP", "H", "V"] },
      { id: "B", text: "For", value: 1, parties: ["MDG"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["Ensomhetspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: ["KrF", "Pensjonistpartiet"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["SV", "R", "Norgesdemokratene", "FrP", "Konservativt", "Generasjonspartiet", "Industri- og Næringspartiet", "Partiet DNI", "FOR", "Sp", "Partiet Sentrum", "Velferd og Innovasjonspartiet"] },
    ],
  },
  {
    id: 7,
    text: "Bør Norge trekke seg fra EØS-avtalen for å styrke nasjonal suverenitet og selvbestemmelse?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["Norgesdemokratene", "SV", "R", "Konservativt", "Industri- og Næringspartiet", "Partiet DNI", "Generasjonspartiet", "Sp", "FOR"] },
      { id: "B", text: "For", value: 1, parties: ["Pensjonistpartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["FrP", "Velferd og Innovasjonspartiet", "Ensomhetspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: ["MDG"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["AP", "H", "KrF", "V", "Partiet Sentrum"] },
    ],
  },
  {
    id: 8,
    text: "Bør staten begrense flyktning- og asylinnvandringen?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["Norgesdemokratene", "Konservativt"] },
      { id: "B", text: "For", value: 1, parties: ["Partiet DNI", "Industri- og Næringspartiet", "FrP", "Generasjonspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["H", "Pensjonistpartiet", "Ensomhetspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: ["V", "Sp"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["AP", "KrF", "SV", "R", "MDG", "FOR", "Partiet Sentrum", "Velferd og Innovasjonspartiet"] },
    ],
  },
  {
    id: 9,
    text: "Bør staten fortsette å finansiere internasjonale bistandsmidler?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["AP", "KrF", "V", "MDG", "Partiet Sentrum"] },
      { id: "B", text: "For", value: 1, parties: ["H", "SV", "R", "Sp", "Pensjonistpartiet", "FOR", "Velferd og Innovasjonspartiet", "Ensomhetspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["Partiet DNI", "Generasjonspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: ["FrP", "Industri- og Næringspartiet"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["Norgesdemokratene", "Konservativt"] },
    ],
  },
  {
    id: 10,
    text: "Bør Norge prioritere olje- og gassutvinning for å sikre nasjonal økonomi fremfor å begrense det på grunn av klima?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["Norgesdemokratene", "FrP", "Konservativt", "Industri- og Næringspartiet", "Partiet DNI"] },
      { id: "B", text: "For", value: 1, parties: ["H"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["Ensomhetspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: ["Sp"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["AP", "KrF", "SV", "R", "MDG", "V", "FOR", "Generasjonspartiet", "Partiet Sentrum", "Pensjonistpartiet", "Velferd og Innovasjonspartiet"] },
    ],
  },
  {
    id: 11,
    text: "Bør klimaendringer prioriteres høyere enn økonomisk vekst i politiske beslutninger?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["MDG", "V", "FOR", "Partiet Sentrum"] },
      { id: "B", text: "For", value: 1, parties: ["AP", "KrF", "SV", "R", "Generasjonspartiet", "Sp", "Pensjonistpartiet", "Velferd og Innovasjonspartiet", "Ensomhetspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["H"] },
      { id: "D", text: "Mot", value: -1, parties: ["FrP"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["Norgesdemokratene", "Konservativt", "Industri- og Næringspartiet", "Partiet DNI"] },
    ],
  },
  {
    id: 12,
    text: "Bør staten øke satsingen på grønn teknologi for å skape nye arbeidsplasser?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["MDG", "Generasjonspartiet", "V", "Partiet Sentrum"] },
      { id: "B", text: "For", value: 1, parties: ["AP", "H", "KrF", "SV", "R", "FOR", "Sp", "Pensjonistpartiet", "Velferd og Innovasjonspartiet", "Ensomhetspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["Industri- og Næringspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: ["FrP"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["Norgesdemokratene", "Konservativt", "Partiet DNI"] },
    ],
  },
  {
    id: 13,
    text: "Bør staten ha mindre innflytelse over skolenes læreplaner for å unngå ideologisk styring?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["Norgesdemokratene", "FrP", "Konservativt", "Generasjonspartiet"] },
      { id: "B", text: "For", value: 1, parties: ["Partiet DNI", "Industri- og Næringspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["H", "V", "Ensomhetspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: ["KrF", "Sp", "MDG"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["AP", "SV", "R", "FOR", "Partiet Sentrum", "Pensjonistpartiet", "Velferd og Innovasjonspartiet"] },
    ],
  },
  {
    id: 14,
    text: "Bør staten avstå fra å finansiere nyhetsmedier og organisasjoner knyttet til livssyn og religion for å sikre uavhengighet og skille staten fra disse områdene?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["Norgesdemokratene", "FrP", "Konservativt", "Partiet DNI"] },
      { id: "B", text: "For", value: 1, parties: ["Industri- og Næringspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["H", "Ensomhetspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: ["Sp", "V", "MDG"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["AP", "KrF", "SV", "R", "FOR", "Generasjonspartiet", "Partiet Sentrum", "Pensjonistpartiet", "Velferd og Innovasjonspartiet"] },
    ],
  },
  {
    id: 15,
    text: "Bør staten begrense regulering av ytringsfrihet, både i lovverk og på digitale plattformer?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["Norgesdemokratene", "Konservativt", "Industri- og Næringspartiet", "Generasjonspartiet", "FrP", "FOR"] },
      { id: "B", text: "For", value: 1, parties: ["V", "Velferd og Innovasjonspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["H", "KrF", "Partiet DNI", "MDG", "R", "Ensomhetspartiet"] },
      { id: "D", text: "Mot", value: -1, parties: ["AP", "Sp"] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["SV", "Partiet Sentrum", "Pensjonistpartiet"] },
    ],
  },
  {
    id: 16,
    text: "Bør Norge forbli i NATO for å sikre nasjonal sikkerhet?",
    options: [
      { id: "A", text: "Sterkt for", value: 2, parties: ["AP", "Norgesdemokratene", "H", "FrP", "V", "Konservativt", "Industri- og Næringspartiet", "Partiet DNI", "Velferd og Innovasjonspartiet"] },
      { id: "B", text: "For", value: 1, parties: ["KrF", "MDG", "Generasjonspartiet", "Sp", "Partiet Sentrum", "Pensjonistpartiet", "Ensomhetspartiet"] },
      { id: "C", text: "Nøytral", value: 0, parties: ["SV"] },
      { id: "D", text: "Mot", value: -1, parties: [] },
      { id: "E", text: "Sterkt mot", value: -2, parties: ["R", "FOR"] },
    ],
  },
];

export const parties = {
  "Norgesdemokratene": { name: "Norgesdemokratene", description: "Parti med fokus på nasjonale interesser og innvandringskontroll." },
  "Konservativt": { name: "Konservativt", description: "Konservativt parti med fokus på tradisjonelle verdier og markedsøkonomi." },
  "Generasjonspartiet": { name: "Generasjonspartiet", description: "Parti med fokus på direktedemokrati." },
  "Industri- og Næringspartiet": { name: "Industri- og Næringspartiet", description: "Parti med fokus på industri og næringsutvikling." },
  "Partiet DNI": { name: "Partiet DNI", description: "Parti med fokus på industri og næringsutvikling." },
  "Pensjonistpartiet": { name: "Pensjonistpartiet", description: "Parti med fokus på pensjonisters rettigheter." },
  "Partiet Sentrum": { name: "Partiet Sentrum", description: "Sentrumsparti med fokus på sosial rettferdighet og miljø." },
  "Velferd og Innovasjonspartiet": { name: "Velferd og Innovasjonspartiet", description: "Parti med fokus på helse, velferd og innovasjon." },
  "FOR": { name: "Fred og Rettferdighet", description: "Parti med fokus på fred og rettferdighet." },
  "Ensomhetspartiet": { name: "Ensomhetspartiet", description: "Parti med fokus på å bekjempe ensomhet." },
  "AP": { name: "Arbeiderpartiet", description: "Sosialdemokratisk parti med fokus på velferd og likhet." },
  "FrP": { name: "Fremskrittspartiet", description: "Liberalistisk folkeparti som fokuserer på lavere skatter, valgfrihet og streng innvandringspolitikk." },
  "H": { name: "Høyre", description: "Sosialkonservativt parti som støtter blandingsøkonomi." },
  "Sp": { name: "Senterpartiet", description: "Sentrumsparti med fokus på distriktspolitikk og landbruk." },
  "KrF": { name: "Kristelig Folkeparti", description: "Kristendemokratisk parti med fokus på familieverdier og velferd." },
  "V": { name: "Venstre", description: "Liberalt parti med fokus på frihet og miljø." },
  "SV": { name: "SV - Sosialistisk Venstreparti", description: "Sosialistisk parti med fokus på velferd og miljø." },
  "R": { name: "Rødt", description: "Venstresideparti med fokus på sosialisme og likhet." },
  "MDG": { name: "Miljøpartiet De Grønne", description: "Miljøparti med fokus på bærekraft og grønn politikk." },
};